name: Deploy Nginx

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-east4-docker.pkg.dev/organic-zephyr-470807-h1/testtrr/nginx:latest .
          docker push us-east4-docker.pkg.dev/organic-zephyr-470807-h1/testtrr/nginx:latest